# File sourced from https://github.com/ystorian/template

[licenses]
# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
version = 2
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "MIT",
    "Unicode-DFS-2016"
]
exceptions = []
