# File sourced from https://github.com/ystorian/template

name: rust

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-stable:
    name: ubuntu-latest - stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Rust toolchain (stable)
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy

      - name: Check
        run: cargo check --all-features

      - name: Build
        run: cargo build --all-features

      - name: Tests
        run: cargo test --all-features

      - name: Format
        run: cargo fmt --all --check

      - name: Lints
        run: cargo clippy --all-targets --all-features -- -W clippy::all -W clippy::pedantic -D warnings

      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1

  checks:
    needs: ubuntu-stable # Only run if the ubuntu-stable job succeeded
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        rust:
          - stable
          - 1.74.1 # MSRV (Minimal Supported Rust Version)
        exclude:
          - os: ubuntu-latest
            rust: stable

    name: ${{ matrix.os }} - ${{ matrix.rust == 'stable' && 'stable' || 'msrv' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Rust toolchain (${{ matrix.rust }})
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
          components: rustfmt, clippy

      - name: Check
        run: cargo check --all-features

      - name: Build
        run: cargo build --all-features

      - name: Tests
        run: cargo test --all-features
